import type { Metadata } from "next";
import localFont from "next/font/local";
import { Manrope} from "next/font/google";
const manrope = Manrope({subsets: ['latin']});

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
// });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.className} bg-background text-primary dark`}>
        {children}
      </body>
    </html>
  );
}
