import type { Metadata } from "next";

import "./globals.css"
import "@pc/ui/globals.css"
import Header from "./components/header";
import LandingSection from "./components/landing-section";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="">
        <Header/>
        <LandingSection/>
        {children}
      </body>
    </html>
  );
}
